### ISSUE TITLE
Destructible eval is not destructible

### ISSUE THREAD

**Issue by donnagf** [pvdz/zeparser3#13]
`const { [eval]: []} = a;`  with and without `"use strict"; ` should pass. 

And same with this non-eval cases `({...{b: 0}.x} = {});` and `({...[0].x} = {});`

**Comment by pvdz** [comment]
The eval cases are accepted (perhaps they were fixed with #12)

I'll address the rest destructuring cases

- [ ] `({...{b: 0}.x} = {});`
- [ ] `({...[0].x} = {});`

**Comment by pvdz** [comment]
I've fixed the rest problems. Core problem is that object pattern rest is more restrictive in its arg than array rest. Meaning that `({...[]}=x)` is invalid while it would be valid for array: `([...[]]=x)`.

Thanks for reporting :)
