### ISSUE TITLE
Should fail on invalid destructuring

### ISSUE THREAD

**Issue by donnagf** [pvdz/zeparser3#16]
- [x] `({a: b => []} = [2])`
- [x] `({a: () => []} = [2])`

- [x] `for([a => {}] in []);`

**Comment by pvdz** [comment]
The second case is already rejecting (or at least, it is now).

The first case seems to relate to the arrow being a property value, since it does not trigger in an array. It's also isolated to the paren-less arrow case. Guess it's not properly propagating its destructibility.

**Comment by pvdz** [comment]
Fixed. Thanks :)
