### ISSUE TITLE
Add missing test cases?

### ISSUE THREAD

**Issue by donnagf** [pvdz/zeparser3#18]
- [ ]  `this.foo[foo].bar(this)(bar)[foo]()--`
- [ ]  `((x,x)) = 5`
- [ ] `(((x,x))) = 5`
- [ ] `async ({a = b})`
- [ ] `++[]`
- [ ] `['++([])`
- [ ] `['(++[])`
- [ ] `++[a]`
- [ ] `[a]++`
- [ ] `[]++`
- [ ] `new Date++;`
- [ ] `for(let.a of 0);`
- [ ] `for (let x in {}) { var x; }`
- [ ] `({...{eval}.x} = {});`
- [ ] `({...{b: 0}.x} = {});`
- [ ] `++[a];`
- [ ] `[...{a = 0}.x] = [];`
- [ ] `({...{b = 0}.x} = {});`
- [ ] `({a: {b = 0}.x} = {});`
- [ ] `[[(x, y)]] = x;`
- [ ] `[...[(x, y)]] = x;`
- [ ] `async (a = b => await (0)) => {}`
- [ ] `(async function*() { } = 1);`
- [ ] `let [(x) = y] = [];`
- [ ] `const [(x)] = []`
- [ ] `let [(x().foo)] = x`
- [ ] `([(x().foo)]) => x`
- [ ] `let [(x) = y] = [];`
- [ ] `let [(x)] = [];`
- [ ] `let {x:o.f=1}={x:1}`
- [ ] `let [o.x=1]=[]`
- [ ] `var [((((a)))), b] = [];`
- [ ] `({...[0].x} = {});`
- [ ] `({...{b: 0}.x} = {});`
- [ ] `({a: {b = 0}.x} = {});`
- [ ] `[...{a = 0}.x] = [];`
- [ ] `[[(x, y)]] = x;`
- [ ] `[...[(x, y)]] = x;`
- [ ] `var [(a)] = 0`
- [ ] `for ({x=1}; 1;) {1}`
- [ ] `[...(a,b)] = []`,
- [ ] `[...{ a }] = b`,
- [ ] `while(true) let[a] = 0`
- [ ] `for (+i in {});`
- [ ] `a[foo].c = () => { throw Error(); };`
- [ ] `/x\ny/`
- [ ] `true:oops;`
- [ ] `for(let.a of 0);`
- [ ] `var\u1680x;`
- [ ] `T‌`
- [ ] `async function foo(a = () => { "use strict"; return eval("x") }) { var x; return a(); }`
- [ ] `/**/ --> comment\n`
- [ ] `for([] = 0 of {});`
- [ ] `for([,] = 0 of {});`
- [ ] `for([a] = 0 of {});`
- [ ] `for([a = 0] = 0 of {});`
- [ ] `for([...a] = 0 of {});`
- [ ] `for([...[]] = 0 of {});`
- [ ] `for([...[a]] = 0 of {});`
- [ ] `for({} = 0 of {});`
- [ ] `for({p: x} = 0 of {});`
- [ ] `for({p: x = 0} = 0 of {});`
- [ ] `for({x} = 0 of {});`
- [ ] `for({x = 0} = 0 of {});`
- [ ] `async function f() { for await ({0: a = 1} = 1 of []) ; }`
- [ ] `async function * f() { for await({a: a = 1} = 1 of []){ } }`
- [ ] `async function * f() { for await({a} = 1 of []){ } }`
- [ ] `async function f() { for await ([a] = 1 of []) ; }`
- [ ] `async function f() { for await ({[Symbol.iterator]: a = 1} = 1 of []) ; }`
- [ ] `for ((a?b:c) in y)z;`
- [ ] `for ((a,b) in c);`
- [ ] `for (((a,b)) in c);`
- [ ] `for ({}.x);`
- [ ] `for ([...[a]] = 0 in {});`

**Comment by pvdz** [comment]
Added to series of tests
