### ISSUE TITLE
Fails / pass on valid / invalid code

### ISSUE THREAD

**Issue by donnagf** [pvdz/zeparser3#2]
I like your code, but way too many bugs / non-failing cases. Let us start. Example object spread doesn't allow destructing, but you allow this :) And also cases like `([{x: y.z}]) => b`, `([{x: y.z}] = a) => b`, and `([{x: y.z} = a]) => b` are not valid, but you allow them.

Also this case should be invalid `[(a = 0)] = 1`

And this one is actually valid, but throws an error in your parser `({a:(b) = 0} = 1)`

**Comment by pvdz** [comment]
I do aim to be perfect so I do appreciate these reports. I will investigate them.

**Comment by pvdz** [comment]
`([{x: y.z}]) => b` and `([{x: y.z}] = a) => b`, `([{x: y.z} = a]) => b`, and `[(a = 0)] = 1` are now properly rejected

One more to go (`({a:(b) = 0} = 1)`)

**Comment by pvdz** [comment]
The range of `({a:(b) = c})` is now resolved. It was incorrectly propagating the assignability of the default expression as well as always marking groups as non-assignable in certain cases.
