### ISSUE TITLE
Unable to assignment destructure the lhs because it is not destructible

### ISSUE THREAD

**Issue by donnagf** [pvdz/zeparser3#22]
Should pass if you try it out on AST Explorer `while ({"a": 2e308.b = function* u() {}} = 8381.11);`

And also for for-statement:

```ts
for (const a of {"": f = ((--false.constructor)), "a": 2e308[((true))] = (() => ({})), b, c = (((false))), qs = ((function () {
}) ? ((/[^+]+/m)) : this)} = (null)) break
```

**Comment by pvdz** [comment]
Seems my fixes from the past week have fixed this. Passes in the repl. Thanks!
