### ISSUE TITLE
Incremental parsing and error recovery?

### ISSUE THREAD

**Issue by donnagf** [pvdz/zeparser3#25]
I have been sick for awhile, and lot of RL issues. Anyways. I looked at your code. Huge changes :)
How do you recover from invalid nodes and avoid throwing errors?

Could a incremental parsing system be a solution? Mark the invalid nodes as dirty and replace them?

**Comment by pvdz** [comment]
I'm sorry to hear that. Hope things are getting better.

Yes the parser has matured quite a bit. If you still find errors please do report them. There is AST parity with Babel and Acorn now. I'm fairly confident on a whole but would not be surprised if there were still problems not covered by tests.

I haven't spent time on error resilience yet. The future idea is to have `THROW` not actually `throw`, and hope the parser just recovers from that. But that's not likely going to work out of the box so will incur some more work to get working. But this is kind of how it worked in ZeParser2 and that was fine. AST will get a little wonky. We'll see.

**Comment by donnagf** [comment]
Just an idea I got when you wrote  AST parity with Babel and Acorn. Wouldn't it be easier to implement a incremental parsing system that have it's own set of rules and AST, and in the end the AST are sent to a transformer kind of thing that output Acorn, Babel etc?  You could probably optimize this too with numbers like I noticed you do with the lexer code now.

For the scanner I noticed your string scanning. Do you need to return different token type for single and double quote? I think it could be simplified into one simple function like "parseString(char)" where char is the "marker". 

I will try to spend the next days looking in depth on your code :)

**Comment by pvdz** [comment]
Yes this is more granular token type is something I have planned. That way you can prevent doing any string matches in the parser but just go off on the data the lexer already knows.

**Comment by donnagf** [comment]
Close this issue? I can't help you for a long time. My lungs collapsed 3 weeks ago and in and out in hospital. Home now :)

**Comment by pvdz** [comment]
I'm sorry to hear that.
I'll close the issue and the issue tracker because I've renamed it to Tenko.

Please take care! Let me know when you're feeling better.
