### ISSUE TITLE
'let' shouldn't be allowed identifier in lexical declarations

### ISSUE THREAD

**Issue by donnagf** [pvdz/zeparser3#4]
This should fail `const [a, let, b] = [1, 2, 3];`. And this similar program actually fails `let [a, let, b] = [1, 2, 3];`

If you try `const {let}` you will see it fails correctly :)

**Comment by pvdz** [comment]
- [ ] `const [a, let, b] = [1, 2, 3];`
- [x] `let [a, let, b] = [1, 2, 3];`
- [x] `const {let} = 1;`

**Comment by pvdz** [comment]
Last case fixed in 8a20ccd180cc6272912b80758a289a1442e06479, closing. Thanks!
