### ISSUE TITLE
Can't destructure parameters to a number

### ISSUE THREAD

**Issue by donnagf** [pvdz/zeparser3#5]
I come across this two programs `([[[[[[[[[[[[[[[[[[[[{a:b[0]}]]]]]]]]]]]]]]]]]]]])=>0;` and `({a:b[0]})=>0`. After checking it in ASTExplorer this should fail if I'm not mistaken.

**Comment by pvdz** [comment]
It should fail because you can't destructure to numbers. Will fix, thanks :)

**Comment by donnagf** [comment]
What about this two? `({"foo": (x) = (1) = "bar"})` and `({"foo": (x) = (1) = "bar"})=>foo`

**Comment by pvdz** [comment]
`({"foo": (x) = (1) = "bar"})` is different, the number should not be assignable and I would expect ZeParser to reject that (*gasp* it doesn't). Ok. It seems to be the difference between `(1)  = "bar"` (properly rejected) and `(a) = (1)  = "bar"` (currently accepted).   

At least the arrow is properly rejected.

--> #7

**Comment by donnagf** [comment]
@pvdz Did you fix this issues? I haven't had time for anything lately, but will try next week if I find more cases. Btw. When do you plan to implement location tracking?

**Comment by pvdz** [comment]
I have not worked much on them this week. Like yourself I only have limited time available to work on these projects right now.

While I do intend to include line/col information to the AST I don't have an ETA on that right now.

**Comment by pvdz** [comment]
The original cases currently fail (this may have been fixed by another commit since being reported).

- [x] `({a:b[0]})=>0`
- [x] `([{a:b[0]}])=>0`
- [x] `([[[[[[[[[[[[[[[[[[[[{a:b[0]}]]]]]]]]]]]]]]]]]]]])=>0`

The other reports were fixed in #7 so this can be closed. Thanks
