### ISSUE TITLE
Object destructuring cases to check

### ISSUE THREAD

**Issue by pvdz** [pvdz/zeparser3#6]
As reported in https://github.com/pvdz/zeparser3/issues/3#issuecomment-471372788

To investigate:

Should all be invalid
- [x] `let {...obj1,} = foo`
- [x] `let {...obj1,a} = foo`
- [x] `let {...obj1,...obj2} = foo`
- [x] `let {...(obj)} = foo`
- [x] `let {...(a,b)} = foo`
- [x] `let {...{a,b}} = foo`
- [x] `let {...[a,b]} = foo`
- [x] `({...obj1,} = foo)`
- [x] `({...obj1,a} = foo)`
- [x] `({...obj1,...obj2} = foo)`
- [x] `({...(a,b)} = foo)`
- [x] `({...{a,b}} = foo)`
- [x] `({...[a,b]} = foo)`
- [x] `({...(obj)}) => {}`
- [x] `({...(a,b)}) => {}`
- [x] `({...{a,b}}) => {}`
- [x] `({...[a,b]}) => {}`
- [x] `({...{}} = {})`

Valid
- [x] `({a:b,...obj}) => {}`
- [x] `({...obj} = {}) => {}`
- [x] `({...(a,b),c})`
- [x] `({...a,b,c})`
- [x] `({...(obj)} = foo)`
- [x] `({...obj} = foo)`
- [x] `({...obj}) => {}`

**Comment by donnagf** [comment]
@pvdz You may as well investigate this `({...{}} = {})`

**Comment by pvdz** [comment]
I'm pretty sure `({...(obj)} = foo)` is legit because it is an assignment pattern, which requires the rest pattern  to be a lhs that is a "simple" `AssignmentTargetType`. The assignment type of a parenthesized lhs is that of the type of the lhs. So in assignment patterns, at least, the rest argument can be wrapped in parentheses without problems.
