### ISSUE TITLE
Assignment to number should always fail

### ISSUE THREAD

**Issue by pvdz** [pvdz/zeparser3#7]
- [x] `(1)  = "bar"`
- [x] `(x) = (1) = "bar"`
- [x] `({"foo": (x) = (1) = "bar"})`
- [x] `({"foo": (x) = (1) = "bar"})=>foo`

**Comment by pvdz** [comment]
Fixed properly throwing for assigning to grouped things that are not assignable: 8dfeaa07387f810a4f3282c63773e3f606157415

**Comment by donnagf** [comment]
I may be stupid, but after trying out your latest changes, you may look into this cases?

```js
for ([...x,] in [[]]) ;
for([] = 0 of {});
for([...[a]] = 0 of {});
for({x} = 0 of {});
for({p: x = 0} = 0 of {});
for(x = 0 in {});
for(o[0] = 0 in {});
```

**Comment by pvdz** [comment]
You're right, these need to be checked and fixed. But that's a different issue from this one because they are related to assignments to the left of the `in` keyword in a `for-in`. --> #8
