### ISSUE TITLE
Assignment in lhs of a `for-in`

### ISSUE THREAD

**Issue by pvdz** [pvdz/zeparser3#8]
- [x] `for ([...x,] in [[]]) ;`
- [x] `for([] = 0 of {});`
- [x] `for([...[a]] = 0 of {});`
- [x] `for({x} = 0 of {});`
- [x] `for({p: x = 0} = 0 of {});`
- [x] `for(x = 0 in {});`
- [x] `for(o[0] = 0 in {});`
- [x] `for ((a++) in c);`
- [x] `for (+a().b in c);`
- [x] `for (void a.b in c);`
- [x] `for (/foo/ in {});`
- [x] ` for ((a in b) in {});`
- [x] `for ((a in b).x in {});`

**Comment by donnagf** [comment]
You may investigate this as well. They fail without the web compability and pass if you enable it. When I tested on AST explorer this cases should all fail? 

```js
for ((a++) in c);
for (+a().b in c);
for (void a.b in c);
for (/foo/ in {});
```

**Comment by pvdz** [comment]
(added to desc)
