### ISSUE TITLE
`a => {} + x`

### ISSUE THREAD

**Issue by pvdz** [pvdz/zeparser3#9]
This is an interesting problem that I've known for a while. The unintuitive part of this example is that the arrow, while in itself a valid expression, is somewhat special syntactically. It came up with regex edge cases, but in this case my parser isn't even doing the actual case properly, let alone the regex case.

To explain we need to look at the arrow first. It is an [`AssignmentExpression`](https://tc39.github.io/ecma262/#prod-AssignmentExpression)

The addition is [AdditiveExpression](https://tc39.github.io/ecma262/#prod-AdditiveExpression): 
AdditiveExpression: AdditiveExpression + MultiplicativeExpression

So we need to check whether an arrow is an `AdditiveExpression` at all. And it is not. Remember that the arrow is in the same category as the actual assignment, `a = b`. In that case, the right hand side is something that could be an `AdditiveExpression`, but the left hand side is not. Arrows are of the type of the left hand side (but could not actually be there due to additional semantic rules).

So, while an arrow is "just an expression", it is one with special rules. This leads to `arrow + x` not being valid. In that vain `arrow / x` is illegal as well, just like `arrow.foo` or `arrow[foo]`, and `arrow()`.

And before you ask, no, it cannot be on the right hand side either. And no the block does not turn into an object.

The issue here is that my parser should not allow parsing an arrow as part of a unary or non-assignment binary expression of any kind. Similar to `yield`, which already gets this treatment to some degree.

**Comment by pvdz** [comment]
I hacked my way around it. Basically querying the current path of the AST to see whether something is being parsed into an arrow. In that case do not allow a tail.

This is the first thing that requires the AST and as such won't work in the AST-less build. Considering the edge case I'm okay with that.

**Comment by donnagf** [comment]
@pvdz What if the arrow is wrapped in parens? Maybe add a few tests for it  `(() => {}) + 2` 
and `(() => {}) ? a : b;`

**Comment by pvdz** [comment]
This should not be a problem (the expression is valid). The problem in solved in this issue was that arrows with a block body cannot have binary operators following it, or anything else, because they are considered assignment expressions. When you wrap them with arrows, the whole thing becomes an expression with which you can do almost anything.
